
eureka:
    client:
        registerWithEureka: true
        festchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
        